apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: rakib-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "ostad"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "ostad"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: rakib-ns
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081

